esphome:
  name: fish-pond-cam-1
  friendly_name: FISH_POND_CAM_1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "68zj+48tgPiazmKNTMXPhWWMedGRmI1dEDnx5Xkr3Qk="

ota:
  password: "93ef3ef97ba52a1803957cae96ca44ae"

wifi:
  ssid: "IOT_2.4G"
  password: "IOTEEB0202"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fish-Pond-Cam-1 Fallback Hotspot"
    password: "LzG00XyfVqwf"

captive_portal:
esp32_camera:
    external_clock:
      pin: GPIO0
      frequency: 20MHz
    i2c_pins:
      sda: GPIO26
      scl: GPIO27
    data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
    vsync_pin: GPIO25
    href_pin: GPIO23
    pixel_clock_pin: GPIO22
    power_down_pin: GPIO32
    name: Camera01
