esphome:
  name: fish-pond-cam-1
  friendly_name: FISH_POND_CAM_1

# Configuration for an ESP32 board, using the Arduino framework
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging for debugging purposes
logger:

# Home Assistant API setup with encryption for secure data transmission
api:
  encryption:
    key: "68zj+48tgPiazmKNTMXPhWWMedGRmI1dEDnx5Xkr3Qk="

# OTA updates configuration with a password for security
ota:
  password: "93ef3ef97ba52a1803957cae96ca44ae"

# WiFi connection details
wifi:
  ssid: "IOT_2.4G"
  password: "IOTEEB0202"

  # Fallback hotspot configuration in case the primary WiFi fails
  ap:
    ssid: "Fish-Pond-Cam-1 Fallback Hotspot"
    password: "LzG00XyfVqwf"

# Captive portal for initial WiFi configuration and troubleshooting
captive_portal:

# ESP32 camera configuration
esp32_camera:
    external_clock:
      pin: GPIO0
      frequency: 20MHz
    i2c_pins:
      sda: GPIO26
      scl: GPIO27
    data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
    vsync_pin: GPIO25
    href_pin: GPIO23
    pixel_clock_pin: GPIO22
    power_down_pin: GPIO32
    name: Camera01
